# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "BlueSignals" = "sha256-VWpu/TKT3duZchitm51X8NlVOtCEqtCk1mah9HMmY/E=";
    "Nanoseconds" = "sha256-sBFCWuMadWkNLZJ9Wy19PbxPvyXQzeKS6DC9l03S9Bc=";
    "Rainbow" = "sha256-g0kwXVfVaKaux8VwKhPQgoFMDJefjGrapvvq3cnjjo0=";
  };
}
